### ISSUE TITLE
Add a small explanation

### ISSUE THREAD

**Issue by muessjoeh** [juliuste/direkt.bahn.guru#18] opened 2022-05-23 10:17 UTC
Now, you only see a map with dots on it. These dots have different colors. 
I suspect that these colors have a meaning. But which one? It would be nice if there was an explanation-

**Comment by juliuste** [comment] 2022-05-23 11:36
Hey (: Thanks for the suggestion, this appears to be a duplicate of #4, will close this issue over the other one. Please re-open if you disagree that this is a duplicate 🙂

**Closed by juliuste** 2022-05-23 11:36 UTC
