### ISSUE TITLE
Map is empty?

### ISSUE THREAD

**Issue by rugk** [juliuste/direkt.bahn.guru#12] opened 2021-12-08 09:29 UTC
![grafik](https://user-images.githubusercontent.com/11966684/145183703-78ec6ac6-c6ae-4eed-b206-791bf80c3541.png)

I just visit https://direkt.bahn.guru/ with Firefox 94.0.
Already disabled some add blockers and see no difference.

**Comment by rugk** [comment] 2021-12-08 09:30
Ah there is a CORS error:
```
10:30:03.597 WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. bundle.js:19801:327915
10:30:04.147 Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://events.mapbox.com/events/v2?access_token=pk.eyJ1IjoianVsaXVzdGUiLCJhIjoiY2t2N3UyeDZ2MjdqZjJvb3ZmcWNyc2QxbSJ9.oB7xzSTcmeDMcl4DhjSl0Q. (Grund: CORS-Anfrage schlug fehl).
10:30:04.385 WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. bundle.js:19801:327915
10:30:04.462 WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. bundle.js:19801:327915
10:30:04.559 WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 4 bundle.js:19801:327915
10:30:04.793 Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://events.mapbox.com/events/v2?access_token=pk.eyJ1IjoianVsaXVzdGUiLCJhIjoiY2t2N3UyeDZ2MjdqZjJvb3ZmcWNyc2QxbSJ9.oB7xzSTcmeDMcl4DhjSl0Q. (Grund: CORS-Anfrage schlug fehl).

```

**Comment by juliuste** [comment] 2021-12-08 17:10
Hey 🙂 Thanks for reporting this, did you enter a station at the top right? If so: Which one?

**Comment by rugk** [comment] 2021-12-08 21:23
No, I just visited the website… :upside_down_face:

**Comment by rugk** [comment] 2021-12-08 22:32
Ahhh I need to enter sth. Very good, now I see what this website is about.

It's basically an isodistance map (yes I also needed to look for this term yet again – and I thouht there was also a wikipedia article for that as there were even hand-drawn maps of this kind before… uhm… "technology happened", but I am getting off-topic…) like https://commutetimemap.com/map.

**Comment by rugk** [comment] 2021-12-08 22:36
Anyway, the CORS errors are likely still a kinda bad sign and should be fixed… :upside_down_face:

**Comment by juliuste** [comment] 2022-05-30 18:46
Regarding CORS errors: This seems to be the result of adblockers like uBlock Origin blocking mapbox event requests (see also: [this issue](https://github.com/mapbox/mapbox-gl-js/issues/11270)), the site should work fine nonetheless, and there is not much I as the site's maintainer can do about the errors appearing in the logs, afaik.

@ElectronicWar regarding the certificate error: I cannot reproduce this, `v5.db.transport.rest` has a valid cert as far as I can tell. Are you sure that everything is "normal" in your certificate setup (e.g. with your list of trusted certificates)?

**Comment by ElectronicWar** [comment] 2022-05-30 19:51
I have re-tried at home and the error was caused by the office network. At home it works with ad-blockers disabled! Sorry for the false alarm.

**Comment by juliuste** [comment] 2022-05-30 19:59
Alright, that's good to hear 🙂! I think all issues reported here are resolved/clarified, so I'll close this for now, please re-open if I missed anything

**Closed by juliuste** 2022-05-30 19:59 UTC
Labels: bug
