### ISSUE TITLE
Suggestion: Filter by connection type

### ISSUE THREAD

**Issue by muessjoeh** [juliuste/direkt.bahn.guru#17] opened 2022-05-23 10:12 UTC
There are some limitations on the type of train I can use, I can only use regional trains, but for example not high speed trains. Since they are not available to me, it would be great if they did not appear as available on the map.

**Comment by juliuste** [comment] 2022-05-24 04:52
Hey (: Thanks for the suggestion, this appears to be a duplicate of #2, will close this issue over the other one. Please re-open if you disagree that this is a duplicate 🙂

**Closed by juliuste** 2022-05-24 04:52 UTC
